version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      day: "monday"
    assignees:
      - "vanyasem"
    reviewers:
      - "vanyasem"
